version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "actions"

  # Maintain Flutter (Pub) dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "flutter"

  # Maintain Gradle (Android) dependencies
  - package-ecosystem: "gradle"
    directory: "/android/app"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "android"
